### ISSUE TITLE
Unexpected behaviour while attempting to check mrc file.

### ISSUE THREAD

**Issue by philipmac** [niaid/tomojs-pytools#37]
```
$ mrc_visual_min_max HUA13_00014_Jan11_patch_aligned_doseweighted.mrc
INFO: Reading "/mnt/ai-fas12/RMLEMHedwigQA/TestData/2DmrcFiles/HUA13_00014_Jan11_patch_aligned_doseweighted.mrc" image information...
WARNING: In /tmp/SimpleITK-build/ITK/Modules/IO/MRC/src/itkMRCHeaderObject.cxx, line 159
MRCHeaderObject (0x55604433bf70): extendedHeaderBytes is: 0If you see this log please contact https://github.com/InsightSoftwareConsortium/ITK/pull/2778

INFO: 	Pixel Type: 32-bit float
INFO: 	Size: (5760, 4092, 1)
INFO: 	Spacing: (0.8636999130249023, 0.8636999726295471, 0.8636999726295471)
INFO: 	Origin:  (0.0, 0.0, 0.0)
INFO: Building histogram for "/mnt/ai-fas12/RMLEMHedwigQA/TestData/2DmrcFiles/HUA13_00014_Jan11_patch_aligned_doseweighted.mrc"...
WARNING: In /tmp/SimpleITK-build/ITK/Modules/IO/MRC/src/itkMRCHeaderObject.cxx, line 159
MRCHeaderObject (0x55604433af30): extendedHeaderBytes is: 0If you see this log please contact https://github.com/InsightSoftwareConsortium/ITK/pull/2778

WARNING: In /tmp/SimpleITK-build/ITK/Modules/IO/MRC/src/itkMRCHeaderObject.cxx, line 159
MRCHeaderObject (0x55604433b370): extendedHeaderBytes is: 0If you see this log please contact https://github.com/InsightSoftwareConsortium/ITK/pull/2778

WARNING: In /tmp/SimpleITK-build/ITK/Modules/IO/MRC/src/itkMRCHeaderObject.cxx, line 159
MRCHeaderObject (0x55604401dbd0): extendedHeaderBytes is: 0If you see this log please contact https://github.com/InsightSoftwareConsortium/ITK/pull/2778

Traceback (most recent call last):
  File "/gs1/home/macmenaminpe/code/hedwig/dev/bin/mrc_visual_min_max", line 8, in <module>
    sys.exit(main())
  File "/gs1/home/macmenaminpe/code/hedwig/dev/lib/python3.9/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/gs1/home/macmenaminpe/code/hedwig/dev/lib/python3.9/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/gs1/home/macmenaminpe/code/hedwig/dev/lib/python3.9/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/gs1/home/macmenaminpe/code/hedwig/dev/lib/python3.9/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/gs1/home/macmenaminpe/code/hedwig/dev/lib/python3.9/site-packages/pytools/ng/build_histogram.py", line 228, in main
    h, bins = stream_build_histogram(input_image, histogram_bin_edges=None)
  File "/gs1/home/macmenaminpe/code/hedwig/dev/lib/python3.9/site-packages/pytools/ng/build_histogram.py", line 109, in stream_build_histogram
    histogram_bin_edges = np.arange(np.iinfo(img_dtype).min - 0.5, np.iinfo(img_dtype).max + 1.5)
  File "/gs1/home/macmenaminpe/code/hedwig/dev/lib/python3.9/site-packages/numpy/core/getlimits.py", line 657, in __init__
    raise ValueError("Invalid integer data type %r." % (self.kind,))
ValueError: Invalid integer data type 'f'.

```

**Comment by blowekamp** [comment]
The command if failing because the input image is float, and it was not initially designed for that pixel type.

To compute a histogram from an image of float will require an additional pass through the data to compute the min/max data range for the bounds and edges of the histogram bins.
