### ISSUE TITLE
mrc_visual_min_max usage query on zarr

### ISSUE THREAD

**Issue by philipmac** [niaid/tomojs-pytools#56]
given:

```
$ ls -l  /tmp/tmpn1_aohf2/2013-1220-dA30_5-BSC-1_10.zarr
total 20
drwxrwxr-x 3 macmenaminpe macmenaminpe 4096 Apr 11 22:17 0
drwxrwxr-x 3 macmenaminpe macmenaminpe 4096 Apr 11 22:17 1
drwxrwxr-x 3 macmenaminpe macmenaminpe 4096 Apr 11 22:18 2
drwxrwxr-x 3 macmenaminpe macmenaminpe 4096 Apr 11 22:18 3
drwxrwxr-x 2 macmenaminpe macmenaminpe 4096 Apr 11 22:17 OME

```
what would be usage?

```
$ mrc_visual_min_max /tmp/tmpn1_aohf2/2013-1220-dA30_5-BSC-1_10.zarr
HDF5-DIAG: Error detected in HDF5 (1.12.1) thread 0:
  #000: /tmp/SimpleITK-build/ITK/Modules/ThirdParty/HDF5/src/itkhdf5/src/H5Fdeprec.c line 156 in itk_H5Fis_hdf5(): unable to determine if file is accessible as HDF5
    major: File accessibility
    minor: Not an HDF5 file
  #001: /tmp/SimpleITK-build/ITK/Modules/ThirdParty/HDF5/src/itkhdf5/src/H5VLcallback.c line 3769 in itk_H5VL_file_specific(): file specific failed
    major: Virtual Object Layer
    minor: Can't operate on object
  #002: /tmp/SimpleITK-build/ITK/Modules/ThirdParty/HDF5/src/itkhdf5/src/H5VLcallback.c line 3699 in H5VL__file_specific(): file specific failed
    major: Virtual Object Layer
    minor: Can't operate on object
  #003: /tmp/SimpleITK-build/ITK/Modules/ThirdParty/HDF5/src/itkhdf5/src/H5VLnative_file.c line 384 in itk_H5VL__native_file_specific(): error in HDF5 file check
    major: File accessibility
    minor: Unable to initialize object
  #004: /tmp/SimpleITK-build/ITK/Modules/ThirdParty/HDF5/src/itkhdf5/src/H5Fint.c line 1086 in itk_H5F__is_hdf5(): error while trying to locate file signature
    major: File accessibility
    minor: Not an HDF5 file
  #005: /tmp/SimpleITK-build/ITK/Modules/ThirdParty/HDF5/src/itkhdf5/src/H5FDint.c line 113 in itk_H5FD_locate_signature(): unable to read file signature
    major: Low-level I/O
    minor: Unable to initialize object
  #006: /tmp/SimpleITK-build/ITK/Modules/ThirdParty/HDF5/src/itkhdf5/src/H5FDint.c line 189 in itk_H5FD_read(): driver read request failed
    major: Virtual File Layer
    minor: Read failed
  #007: /tmp/SimpleITK-build/ITK/Modules/ThirdParty/HDF5/src/itkhdf5/src/H5FDsec2.c line 755 in H5FD__sec2_read(): file read failed: time = Wed Apr 12 21:41:02 2023
, filename = '/tmp/tmpn1_aohf2/2013-1220-dA30_5-BSC-1_10.zarr', file descriptor = 3, errno = 21, error message = 'Is a directory', buf = 0x7fff7fe7af48, total read size = 8, bytes this sub-read = 8, bytes actually read = 18446744073709551615, offset = 0
    major: Low-level I/O
    minor: Read failed
Traceback (most recent call last):
  File "/home/macmenaminpe/code/hedwig/dev/bin/mrc_visual_min_max", line 8, in <module>
    sys.exit(main())
  File "/home/macmenaminpe/code/hedwig/dev/lib/python3.8/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/home/macmenaminpe/code/hedwig/dev/lib/python3.8/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/home/macmenaminpe/code/hedwig/dev/lib/python3.8/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/macmenaminpe/code/hedwig/dev/lib/python3.8/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/home/macmenaminpe/code/hedwig/dev/lib/python3.8/site-packages/pytools/ng/build_histogram.py", line 370, in main
    img = sitk.ReadImage(input_image)
  File "/home/macmenaminpe/code/hedwig/dev/lib/python3.8/site-packages/SimpleITK/extra.py", line 368, in ReadImage
    return reader.Execute()
  File "/home/macmenaminpe/code/hedwig/dev/lib/python3.8/site-packages/SimpleITK/SimpleITK.py", line 8846, in Execute
    return _SimpleITK.ImageFileReader_Execute(self)
RuntimeError: Exception thrown in SimpleITK ImageFileReader_Execute: /tmp/SimpleITK/Code/IO/src/sitkImageReaderBase.cxx:105:
sitk::ERROR: Unable to determine ImageIO reader for "/tmp/tmpn1_aohf2/2013-1220-dA30_5-BSC-1_10.zarr"

```
assuming I'm using incorrectly

**Comment by blowekamp** [comment]
The following is what is used to detect a zarr array:
https://github.com/niaid/tomojs-pytools/blob/master/pytools/ng/build_histogram.py#L360

I suppose an informative warning could be added it ".zarr" is contained in the path but the ".zarray" file is not there as expected.

**Comment by philipmac** [comment]
Usage: 
`mrc_visual_min_max --mad 5 /tmp/tmpn1_aohf2/2013-1220-dA30_5-BSC-1_10.zarr/0/`
