### ISSUE TITLE
TypeError: dtype: >u2 is not supported as an array.

### ISSUE THREAD

**Issue by annshress** [niaid/tomojs-pytools#81]
Log file (needs vpn connection): https://prefect1.hedwig-workflow-api.niaiddev.net/default/task-run/d5a09c0b-d9f9-4f15-b682-723b6fb2694b?logs

```
Traceback (most recent call last):
  File "/gs1/home/hedwig_dev/dev/lib/python3.10/site-packages/SimpleITK/extra.py", line 245, in _get_sitk_vector_pixelid
    return _np_sitk[numpy_array_type.dtype]
KeyError: dtype('>u2')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/gs1/home/hedwig_dev/dev/lib/python3.10/site-packages/prefect/engine/task_runner.py", line 880, in get_task_run_state
    value = prefect.utilities.executors.run_task_with_timeout(
  File "/gs1/home/hedwig_dev/dev/lib/python3.10/site-packages/prefect/utilities/executors.py", line 468, in run_task_with_timeout
    return task.run(*args, **kwargs)  # type: ignore
  File "<string>", line 103, in generate_czi_imageset
  File "<string>", line 77, in gen_imageSet
  File "<string>", line 36, in gen_thumb
  File "/gs1/home/hedwig_dev/dev/lib/python3.10/site-packages/pytools/HedwigZarrImage.py", line 170, in extract_2d
    img = sitk.GetImageFromArray(arr.compute(), isVector=is_vector)
  File "/gs1/home/hedwig_dev/dev/lib/python3.10/site-packages/SimpleITK/extra.py", line 311, in GetImageFromArray
    id = _get_sitk_vector_pixelid(z)
  File "/gs1/home/hedwig_dev/dev/lib/python3.10/site-packages/SimpleITK/extra.py", line 247, in _get_sitk_vector_pixelid
    raise TypeError('dtype: {0} is not supported as an array.'.format(numpy_array_type.dtype))
TypeError: dtype: >u2 is not supported as an array.
```

.zarr file in consideration: The zarr file: /mnt/ai-fas12/RMLEMHedwigDev/Assets/TEST/shress/test-2023-09-29-TK/CZI-stuffs/DD/KC_M3_S2_ReducedImageSubset1/KC_M3_S2_ReducedImageSubset1.zarr

All `.zarray` in the zarr file show `>u2` as their data types.

**Comment by blowekamp** [comment]
Has this pipeline worked with other input images? Or is this error happening with all?

Also please check the version/hash of the code installed.

**Comment by blowekamp** [comment]
This like should be converting the array to a native type: https://github.com/niaid/tomojs-pytools/blob/52e17d294a6b56925316effd031b36d452dc361a/pytools/HedwigZarrImage.py#L163

**Comment by annshress** [comment]
This is happening with other image that I have tested with as well.

**Comment by blowekamp** [comment]
I was not able to reproduce the error with the following test script:
```
import pytools
from pathlib import Path

fn = Path("/mnt/ai-fas12/RMLEMHedwigDev/Assets/TEST/shress/test-2023-09-29-TK/CZI-stuffs/DD/KC_M3_S2_ReducedImageSubset1/KC_M3_S2_ReducedImageSubset1.zarr")

zimgs = pytools.HedwigZarrImages(fn)
for k, zi in zimgs.series():
    print(f"exracting {k}")
    zi = zimgs[k]
    img = zi.extract_2d(200,200)
    print(img)

```

**Comment by blowekamp** [comment]
The issues appears to only occur in a distributed Dask environment. The above PR addressed the issue.
